# Generated by Django 2.2.2 on 2019-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190726_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='googledocid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
