# Generated by Django 2.2.2 on 2019-08-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
