# Generated by Django 2.2.2 on 2019-08-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='googledocid',
            new_name='image_uri',
        ),
    ]
