# Generated by Django 2.2.2 on 2019-08-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('googledocid', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
