# Generated by Django 2.2.2 on 2019-09-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('email_address', models.CharField(max_length=254)),
                ('vipstarcoin_address', models.CharField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
